### ISSUE TITLE
启动后，持续不断的收到重复的报错信息

### ISSUE THREAD

**Issue by linchen1987** [blocklet/ocap-playground#129]
服务可正常访问，但是一直收到报错信息

```
2022-01-14T14:57:08: Error: listen EADDRINUSE: address already in use :::8122

2022-01-14T14:57:08:     at Server.setupListenHandle [as _listen2] (net.js:1318:16)

2022-01-14T14:57:08:     at listenInCluster (net.js:1366:12)

2022-01-14T14:57:08:     at Server.listen (net.js:1452:7)

2022-01-14T14:57:08:     at Function.listen (/data/.abtnode/blocklets/promotion-tool/0.1.4/node_modules/express/lib/application.js:618:24)

2022-01-14T14:57:08:     at Object.<anonymous> (/data/.abtnode/blocklets/promotion-tool/0.1.4/server/index.js:58:5)

2022-01-14T14:57:08:     at Module._compile (internal/modules/cjs/loader.js:1063:30)

2022-01-14T14:57:08:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

2022-01-14T14:57:08:     at Module.load (internal/modules/cjs/loader.js:928:32)

2022-01-14T14:57:08:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)

2022-01-14T14:57:08:     at Module.require (internal/modules/cjs/loader.js:952:19) {

2022-01-14T14:57:08:   code: 'EADDRINUSE',

2022-01-14T14:57:08:   errno: -98,

2022-01-14T14:57:08:   syscall: 'listen',

2022-01-14T14:57:08:   address: '::',

2022-01-14T14:57:08:   port: 8122

2022-01-14T14:57:08: }
```

**Comment by wangshijun** [comment]
这不是 ocap-playground 的问题么？看 error stack 是 @NateRobinson 那边的 blocklet？

**Comment by linchen1987** [comment]
是 promotion blocklet, 因为 promotion 被组合在 ocap-playground 下了，所以在 playground 的 error log 中看到日志

**Comment by wangshijun** [comment]
不再有效
