### ISSUE TITLE
send notification 报错

### ISSUE THREAD

**Issue by linchen1987** [blocklet/ocap-playground#18]
- dev node 中的 wallet-playground 发动 asset notification 和 token notification 时报错。 
- 在本地 node 中的 wallet-playground 正常，本地 wallet-playground 的配置和 dev node 中的 wallet-playground 相同。
- wallet-playground 版本：0.8.3

错误信息：

send asset
```
2021-05-17T02:26:34: Error: GraphQLError: Invalid state extracted for z1YMQ5jRtTurxyAZPLhg3qh4yfyf93zQDeP

2021-05-17T02:26:34:     at NativeGraphqlClient._doRequest (/data/.abtnode/blocklets/ocap-playground/0.8.3/node_modules/@ocap/client/node_modules/@arcblock/sdk-util/lib/index.js:315:21)

2021-05-17T02:26:34:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

2021-05-17T02:26:34:     at async /data/.abtnode/blocklets/ocap-playground/0.8.3/node_modules/@ocap/client/lib/extension.js:343:30 {

2021-05-17T02:26:34:   errors: [

2021-05-17T02:26:34:     {

2021-05-17T02:26:34:       code: 'INVALID_RECEIVER_STATE',

2021-05-17T02:26:34:       message: 'Invalid state extracted for z1YMQ5jRtTurxyAZPLhg3qh4yfyf93zQDeP',

2021-05-17T02:26:34:       locations: [Array],

2021-05-17T02:26:34:       stack: [],

2021-05-17T02:26:34:       path: [Array]

2021-05-17T02:26:34:     }

2021-05-17T02:26:34:   ]

2021-05-17T02:26:34: }
```

send token
```
2021-05-17T02:27:44: Error: GraphQLError: Invalid state extracted for z1YMQ5jRtTurxyAZPLhg3qh4yfyf93zQDeP

2021-05-17T02:27:44:     at NativeGraphqlClient._doRequest (/data/.abtnode/blocklets/ocap-playground/0.8.3/node_modules/@ocap/client/node_modules/@arcblock/sdk-util/lib/index.js:315:21)

2021-05-17T02:27:44:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

2021-05-17T02:27:44:     at async /data/.abtnode/blocklets/ocap-playground/0.8.3/node_modules/@ocap/client/lib/extension.js:343:30 {

2021-05-17T02:27:44:   errors: [

2021-05-17T02:27:44:     {

2021-05-17T02:27:44:       code: 'INVALID_RECEIVER_STATE',

2021-05-17T02:27:44:       message: 'Invalid state extracted for z1YMQ5jRtTurxyAZPLhg3qh4yfyf93zQDeP',

2021-05-17T02:27:44:       locations: [Array],

2021-05-17T02:27:44:       stack: [],

2021-05-17T02:27:44:       path: [Array]

2021-05-17T02:27:44:     }

2021-05-17T02:27:44:   ]

2021-05-17T02:27:44: }
```

**Comment by wangshijun** [comment]
这个仅仅是登录了 playground 的钱包？看报错是账户没有链上 declare

**Comment by linchen1987** [comment]
在发送通知前检查下

ocap-playground 测试用例里面

调 SDK.getAccountState({ address: userDid }) 看结果里面的 state 属性

如果为空的话，给前端宝格措

给前端报个错
